name: Build Docker Image
on:
  pull_request:
    branches:
      - main
    paths:
      - app/**
      - .dockerignore
      - .Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
